# Generated by Django 5.2.3 on 2025-06-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='immage',
            new_name='immagine',
        ),
    ]
